In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
data=pd.read_csv("Dataset.csv")

In [3]:
data

Position  Hours of study  Marks scored
0   Group-1               1            45
1   Group-2               2            50
2   Group-3               3            60
3   Group-4               4            80
4   Group-5               5           110
5   Group-6               6           150
6   Group-7               7           200
7   Group-8               8           300
8   Group-9               9           500
9  Group-10              10          1000

In [6]:
X=data.iloc[:,1:2].values
y=data.iloc[:,-1].values

In [7]:
print(X)
print(y)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[  45   50   60   80  110  150  200  300  500 1000]


In [8]:
#in this algorithm we don't split data into train and test
from sklearn.tree import DecisionTreeRegressor
regeressor=DecisionTreeRegressor()
regeressor.fit(X,y)

DecisionTreeRegressor()

In [11]:
y_predict=regeressor.predict([[11]])
y_predict

array([1000.])